### ISSUE TITLE
Client - server mismatch

### ISSUE THREAD

**Issue by nebain** [cullenjett/react-ssr-boilerplate#9] opened 2018-11-08 19:21 UTC
This boilerplate code looks great! I came across it while I was wrestling a problem in my own homemade solution and finally threw up my hands to see how others were doing it. Unfortunately, I am having the same problem with your boilerplate.

```
git clone ...
cp .env_SAMPLE .env
npm install
npm run start
```
When I load localhost:3000/ in Chrome, I get the following error in the console:

```
Warning: Text content did not match. Server: "Home page" Client: "Loading..."
```

It's as if `Loadable.preloadReady()` isn't actually working on the client side. I wish I could submit an issue on the react-loadable project, but that's apparently disabled. Any idea what's going on here?

**Comment by cullenjett** [comment] 2018-11-08 20:20
Well crap, it seems like I re-create this bug on a regular basis (can't wait for React Suspense to land). It looks like my most recent release (`2.11.0`) introduced it -- I locally rolled back to the [2.10.1 release](https://github.com/cullenjett/react-ssr-boilerplate/tree/v2.10.1) and it wasn't throwing that error. 

In this most recent release I slightly changed how the app is initialized so I'm betting the issue is hiding in there somewhere (`src/index.js` and `src/main.js`), I'll try to investigate soon and get a fix pushed up.

**Comment by nebain** [comment] 2018-11-08 20:59
I found the issue - in `2.10.1` you used a window.render hack. When I added that hack back in to `2.11.0`, the issue went away. Unfortunately, that hack doesn't seem to be fixing my existing project. And, of course, there is the question of why the hack is necessary in the first place.

**Comment by nebain** [comment] 2018-11-09 01:57
Okay, so I found the real issue. Scratch my previous comment. In `indexHtml.js`, you have:

```
return [mainJS, ...bundleFilePaths]
```

The order needs to be reversed so that all the bundles are loaded before mainJS. That is,

```
return [...bundleFilePaths, mainJS]
```

**Comment by cullenjett** [comment] 2018-11-18 18:56
@nebain Thanks for digging into this and letting me know, I really appreciate it! I've pushed up your suggested fix (which worked great), so I'll go ahead and close this issue.

**Closed by cullenjett** 2018-11-18 18:56 UTC
